phonemes_to_index = {'AA': 0, 'AE': 1, 'AH': 2, 'AO': 3, 'AW': 4, 'AY': 5, 'B': 6, 'CH': 7, 'D': 8, 'DH': 9, 'EH': 10,
                     'ER': 11, 'EY': 12, 'F': 13, 'G': 14, 'HH': 15, 'IH': 16, 'IY': 17, 'JH': 18, 'K': 19, 'L': 20,
                     'M': 21, 'N': 22, 'NG': 23, 'OW': 24, 'OY': 25, 'P': 26, 'R': 27, 'S': 28, 'SH': 29, 'T': 30,
                     'TH': 31, 'UH': 32, 'UW': 33, 'V': 34, 'W': 35, 'Y': 36, 'Z': 37, 'ZH': 38}
index_to_phonemes = {v: k for k, v in phonemes_to_index.items()}

TIMIT_61_39 = {'aa': 'aa',
       'ae': 'ae',
       'ah': 'ah',
       'ao': 'aa',
       'aw': 'aw',
       'ax': 'ah',
       'ax-h': 'ah',
       'axr': 'er',
       'ay': 'ay',
       'b': 'b',
       'bcl': 'sil',
       'ch': 'ch',
       'd': 'd',
       'dcl': 'sil',
       'dh': 'dh',
       'dx': 'dx',
       'eh': 'eh',
       'el': 'l',
       'em': 'm',
       'en': 'n',
       'eng': 'ng',
       'epi': 'sil',
       'er': 'er',
       'ey': 'ey',
       'f': 'f',
       'g': 'g',
       'gcl': 'sil',
       'h#': 'sil',
       'hh': 'hh',
       'hv': 'hh',
       'ih': 'ih',
       'ix': 'ih',
       'iy': 'iy',
       'jh': 'jh',
       'k': 'k',
       'kcl': 'sil',
       'l': 'l',
       'm': 'm',
       'n': 'n',
       'ng': 'ng',
       'nx': 'n',
       'ow': 'ow',
       'oy': 'oy',
       'p': 'p',
       'pau': 'sil',
       'pcl': 'sil',
       'q': 'sil',
       'r': 'r',
       's': 's',
       'sh': 'sh',
       't': 't',
       'tcl': 'sil',
       'th': 'th',
       'uh': 'uh',
       'uw': 'uw',
       'ux': 'uw',
       'v': 'v',
       'w': 'w',
       'y': 'y',
       'z': 'z',
       'zh': 'sh'}

